app:
  name: apigateway
  read_timeout: 10
  write_timeout: 10
  connect_timeout: 10
  default_news_limit: 10
  processing_interval: "3m"
  feed_urls:
    - name: dev.to
      url: https://dev.to/feed
    - name: bbci.com
      url: http://feeds.bbci.co.uk/news/rss.xml
    - name: nytimes.com
      url: https://rss.nytimes.com/services/xml/rss/nyt/World.xml
    - name: ria.ru
      url: https://ria.ru/export/rss2/index.xml

http:
  host: 0.0.0.0
  port: 8080

logging:
  level: debug
  format: text

database:
  # Пример конфигурации БД (не используется API Gateway напрямую, но хранится централизованно)
  host: localhost
  port: 5432
  username: news
  password: password
  dbname: news_db
  sslmode: disable

kafka:
  brokers:
    - localhost:9092
  topics:
    news_input: news_input
    news_list: newslist
    news_detail: newsdetail
    filtered_content: filtered_content
    filter_published: filter_published
    comments_input: comments_input
    add_comments: add_comments
    comments: comments
  consumer_groups:
    gnews: gnews
    api_gateway: api-gateway
    comments: comments

server:
  address: ":8080"

routes:
  - name: newsservice
    base_url: http://localhost:6000
  - name: commentservice
    base_url: http://localhost:7000
  - name: censorservice
    base_url: http://localhost:5000

